version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=data
      - DATASET_PATH=/app/TrainingData/Student_data.csv
    restart: unless-stopped
